name: clang-llvm-toolchain

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LLVM GitHub Release Version'
        required: true 
        type: string

jobs:
  build-clang-llvm-toolchain:
    runs-on: ubuntu-latest
    steps:
      # - run: sudo apt-get update && sudo apt-get install -y curl build-essential python3 python3-distutils cmake ninja-build
      - run: uname -a
      - run: pwd
      - run: llvm-project
      # - run: curl --location https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ inputs.version }}/llvm-project-${{ inputs.version }}.src.tar.xz -o /home/llvm-project.tar.xz
      # - run: tar -xf /home/llvm-project.tar.xz -C /home/llvm-project --strip-components 1
      # - run: ls /home/llvm-project