name: clang-llvm-toolchain

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LLVM GitHub Release Version'
        required: true 
        type: string

jobs:
  build-clang-llvm-toolchain:
    runs-on: ubuntu-latest
    steps:
      # - run: sudo apt-get update && sudo apt-get install -y curl build-essential python3 python3-distutils cmake ninja-build
      - run: uname -a
      - run: pwd
      - run: mkdir llvm-project
      - run: curl --location https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ inputs.version }}/llvm-project-${{ inputs.version }}.src.tar.xz -o llvm-project.tar.xz
      - run: tar -xf llvm-project.tar.xz -C llvm-project --strip-components 1
      - run: perl -pi -e 's/#if __LDBL_MANT_DIG__ == 113 && defined\(__SIZEOF_INT128__\)/#if (__LDBL_MANT_DIG__ == 113 || defined(__x86_64__)) && defined(__SIZEOF_INT128__)/g' llvm-project/compiler-rt/lib/builtins/fp_lib.h
      - run: perl -pi -e 's/typedef long double fp_t;/#if defined(__FLOAT128__) || defined(__SIZEOF_FLOAT128__)\ntypedef __float128 fp_t;\n#else\ntypedef long double fp_t;\n#endif/g' llvm-project/compiler-rt/lib/builtins/fp_lib.h
      - run: cat llvm-project/compiler-rt/lib/builtins/fp_lib.h